# Site Settings
baseurl: 		""
title: 			Hashtag for Jekyll

name: 			Hashtag <i>for</i> Jekyll
description: 	A beautifully contemporary and elegant Jekyll theme
url: 			"http://localhost:4000"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Indiqo.	

# Build Settings
permalinks: 	pretty