# Site Settings
baseurl: 		""
title: 			Flish.uk

name: 			Flish
description: 	These are not the workds you're looking for
url: 			"http://localhost:4000"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		andyflisher
email: 			webmaster@flish.uk

disqus: 		andyflisher
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright Flish

# Build Settings
permalinks: 	pretty
